/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.roboracers.gaeldrive;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
